### ISSUE TITLE
[feature] - Data warehouse

### ISSUE THREAD

**Issue by nicolamassarenti** [nicolamassarenti/ml-kafka-rust#21]
# Description of the feature
Identify and integrate a data warehouse for analytics

# Motivation for the feature
Given the existence of a dashboard and given that the data arrive in a streaming fashion, a fast data warehouse is needed.

# Additional context
It must:
* work on a lightweight hardware (my laptop)
* be open source

# Tasks
The list of tasks to be done for this feature to be completed is:
* [ ] Choose a data warehouse
* [ ] Create the data warehouse service
* [ ] Add the data warehouse to docker-compose
