### ISSUE TITLE
[feature] - Database for metrics

### ISSUE THREAD

**Issue by nicolamassarenti** [nicolamassarenti/ml-kafka-rust#25]
# Description of the feature
Identify and choose a database for metrics. 

# Motivation for the feature
Given the existence of a dashboard, a database for metrics is needed

# Tasks
The list of tasks to be done for this feature to be completed is:
* [ ] Choose a database for storing the metrics
* [ ] Implement the database service
* [ ] Add the database to docker-compose
