### ISSUE TITLE
[feature] - Dashboard

### ISSUE THREAD

**Issue by nicolamassarenti** [nicolamassarenti/ml-kafka-rust#38]
# Description of the feature
Develop a dashboard with minimal functionalities that allows the user to:
* Monitor the monitoring KPIs
* Monitor the model predictions

# Motivation for the feature
The dashboard allows a user to analyse the system performance

# Additional context
If possible, use easy-to-use and no-code frameworks

# Tasks
The list of tasks to be done for this feature to be completed is:
* [ ] Identify and choose the technology
* [ ] Implement the front end
* [ ] Create the container
* [ ] Add the front end to the docker compose
